### ISSUE TITLE
Component: Book grid view

### ISSUE THREAD

**Issue by aklt** [solsort/mobibl#17]
Horizontally scrollable?

**Comment by jacobandresen** [comment]
One approach to do this could be via a susy gallery. http://susydocs.oddbird.net/en/latest/toolkit/

**Comment by rasmuserik** [comment]
I ended up using the responsive grid from semantic-ui, search results and related, and a horisontally-scrolling line similar to the original wireframe for the work-history #67.

Also, it looks better with the text beside the cover as in result/related, rather than my original wireframes, imho. When #65 and #67 is merged the difference is clearly visible on the `work`-page, which has both.
